### ISSUE TITLE
w3c benchmark: NoSuchElementException: BoundJoinIterator

### ISSUE THREAD

**Issue by Rintarou** [Callidon/sage-jena#3]
When running queries
bindings/values01, bindings/values05, bindings/inline01, bind/bind11, entailment/bind03, functions/bnode01
from the [w3c SPARQL 1.1 compliance benchmark](https://www.w3.org/2009/sparql/implementations/)

we obtain the following error output:
```
Exception in thread "main" java.util.NoSuchElementException: BoundJoinIterator
 	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.nextBinding(QueryIteratorBase.java:158)
 	at org.apache.jena.sparql.engine.iterator.QueryIterConvert.moveToNextBinding(QueryIterConvert.java:64)
 	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.nextBinding(QueryIteratorBase.java:156)
 	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.moveToNextBinding(QueryIteratorWrapper.java:42)
 	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.nextBinding(QueryIteratorBase.java:156)
 	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.moveToNextBinding(QueryIteratorWrapper.java:42)
 	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.nextBinding(QueryIteratorBase.java:156)
 	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.next(QueryIteratorBase.java:131)
 	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.next(QueryIteratorBase.java:40)
 	at org.apache.jena.sparql.engine.ResultSetStream.nextBinding(ResultSetStream.java:86)
 	at org.apache.jena.sparql.engine.ResultSetStream.nextSolution(ResultSetStream.java:114)
 	at org.apache.jena.sparql.engine.ResultSetStream.next(ResultSetStream.java:123)
 	at org.apache.jena.sparql.engine.ResultSetCheckCondition.next(ResultSetCheckCondition.java:61)
 	at org.apache.jena.sparql.resultset.ResultSetApply.apply(ResultSetApply.java:39)
 	at org.apache.jena.riot.resultset.rw.ResultSetWriterXML.write(ResultSetWriterXML.java:82)
 	at org.apache.jena.riot.resultset.rw.ResultsWriter.write(ResultsWriter.java:127)
 	at org.apache.jena.riot.resultset.rw.ResultsWriter.write(ResultsWriter.java:97)
 	at org.apache.jena.riot.resultset.rw.ResultsWriter$Builder.write(ResultsWriter.java:71)
 	at org.apache.jena.query.ResultSetFormatter.output(ResultSetFormatter.java:320)
 	at org.apache.jena.query.ResultSetFormatter.outputAsXML(ResultSetFormatter.java:347)
 	at org.apache.jena.query.ResultSetFormatter.outputAsXML(ResultSetFormatter.java:338)
 	at org.gdd.sage.cli.SelectQueryExecutor.execute(SelectQueryExecutor.java:26)
	at org.gdd.sage.cli.CLI.main(CLI.java:74)
```

The different queries are as follow:
* bindings/values01
```sparql
PREFIX dc:   <http://purl.org/dc/elements/1.1/> 
PREFIX :     <http://example.org/book/> 
PREFIX ns:   <http://example.org/ns#> 

SELECT ?book ?title ?price
{
   ?book dc:title ?title ;
         ns:price ?price .
}
VALUES ?book {
 :book1
}
```
* bindings/values05
```sparql
PREFIX : <http://example.org/> 

SELECT ?s ?o1 ?o2
{
  ?s ?p1 ?o1 .
  ?s ?p2 ?o2 .
} VALUES (?o1 ?o2) {
 (UNDEF "Alan")
 (:b UNDEF)
}
```
* bindings/inline01
```sparql
PREFIX dc:   <http://purl.org/dc/elements/1.1/> 
PREFIX :     <http://example.org/book/> 
PREFIX ns:   <http://example.org/ns#> 

SELECT ?book ?title ?price
{
   VALUES ?book { :book1 }
   ?book dc:title ?title ;
         ns:price ?price .
}
```
* bind/bind11
```sparql
PREFIX : <http://example.org/> 

SELECT ?s ?v ?z
{
  # See also bind10.rq
  BIND(4 AS ?z)
  # ?z is in scope at the time of filter execution.
  ?s :p ?v . 
  FILTER(?v = ?z)
}
```
* entailment/bind03
```sparql
PREFIX : <http://example.org/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?z ?s1
{
  ?s ?p ?o .
  ?p a owl:DatatypeProperty . 
  BIND(?o+1 AS ?z)
  ?s1 ?p1 ?z .
  ?p1 a owl:DatatypeProperty . 
}
```
* functions/bnode01
```sparql
PREFIX : <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?s1 ?s2
(BNODE(?s1) AS ?b1) (BNODE(?s2) AS ?b2)
WHERE {
	?a :str ?s1 .
	?b :str ?s2 .
	FILTER (?a = :s1 || ?a = :s3)
	FILTER (?b = :s1 || ?b = :s3)
}
```

There are multiple reasons for why this is of concern:
* previous iterations of the sage-jena did not trigger this. meaning this is a flat regression
* Results (even wrong ones) are not produced any more, as a consequence, we cannot debug the queries for their actual treatment issues.
* The different queries that trigger this bug are widely different, and it does not seem like there is a connecting factor between them.

If required i might be able to produce evidence of working keywords, ruling them out as source of the problem. But it might also not be feasible, as working keywords could still be causing the bugs because of the context they are used in.

attached are the Queries that trigger the issue
[QRE.zip](https://github.com/Callidon/sage-jena/files/2192510/QRE.zip)

This is unlikely to be related to Jena, as most queries run fine on Jena-hdt.

**Comment by Rintarou** [comment]
After correcting a problem in the testing process, the issue is only affecting
entailment/bind03, bind/bind03 and service/service07.
new issues have been revealed in some of the old concerned files (values05, bnode01).

the new concerned queries feature the **BIND** keyword, or the **SERVICE SILENT** keyword. It is still unclear why it occurs, but it no longer is such a big concern as:
*. the queries are no longer widely different
*. it seems the bug was in the code, but was exacerbated by a fault in the testing process

The only remaining issue with it is that is stops from debugging/checking the query for its validity

**Comment by Rintarou** [comment]
After correcting a problem in the testing process, the issue is only affecting
entailment/bind03, bind/bind03 and service/service07.
new issues have been revealed in some of the old concerned files (values05, bnode01).

the new concerned queries feature the **BIND** keyword, or the **SERVICE SILENT** keyword. It is still unclear why it occurs, but it no longer is such a big concern as:
*. the queries are no longer widely different
*. it seems the bug was in the code, but was exacerbated by a fault in the testing process

The only remaining issue with it is that is stops from debugging/checking the query for its validity

**Comment by Rintarou** [comment]
Issue is fixed. The java.util.NoSuchElementException: BoundJoinIterator
is not thrown by any process after a full run of the tests.

Closing the issue.
